// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLh9LRpGdMTzDT8nICZx2j2FZVqeqLc0',
    appId: '1:78221884421:web:6ddce77a66aaff610df06c',
    messagingSenderId: '78221884421',
    projectId: 'todos-fa13a',
    authDomain: 'todos-fa13a.firebaseapp.com',
    storageBucket: 'todos-fa13a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMzComVWU5plAj2FxxMBB5Wo1k2pix_AU',
    appId: '1:78221884421:android:d9b4b0d0764a8bf10df06c',
    messagingSenderId: '78221884421',
    projectId: 'todos-fa13a',
    storageBucket: 'todos-fa13a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4YewSR2PPSO25DB-1LMj15wV-OZnCjJQ',
    appId: '1:78221884421:ios:feb8ac719434850c0df06c',
    messagingSenderId: '78221884421',
    projectId: 'todos-fa13a',
    storageBucket: 'todos-fa13a.appspot.com',
    iosBundleId: 'com.example.toDos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4YewSR2PPSO25DB-1LMj15wV-OZnCjJQ',
    appId: '1:78221884421:ios:fa559b7b29cc1b2c0df06c',
    messagingSenderId: '78221884421',
    projectId: 'todos-fa13a',
    storageBucket: 'todos-fa13a.appspot.com',
    iosBundleId: 'com.example.toDos.RunnerTests',
  );
}
